using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;
using TrinityTej;
using System.IO;
using System.Security.AccessControl;
using System.Text.RegularExpressions;
public partial class Student_reg_form : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!Page.IsPostBack)
        {
            try
            {
                fillcourse();
            }
            catch (Exception ex)
            {
               
            }
        }
    }
    protected void btn_clear_Click(object sender, EventArgs e)
    {
        ClearTextBox();
    }

    #region(Function to Clear Controls After data Submision)
    public void ClearTextBox()
    {
        txt_email.Text = "";
        txt_studentname.Text = ""; txt_login_expiry_Date.Text = "";
        txt_FatherName.Text = "";
        txt_occupation.Text = ""; 
        txt_Presentadd.Text = ""; txt_email.Text = "";
        txt_Emergency.Text = ""; txt_Phone.Text = ""; ddlgender.SelectedIndex = 0; txtenrollment.Text = ""; ddlcourse.SelectedIndex = 0;
    }
    #endregion

    protected void btn_submit_Click(object sender, EventArgs e)
    {
        #region(Student Record Save in database)
        try
        {

            string enrollment = txtenrollment.Text;
            string Password = txtpassword.Text;
            string course = ddlcourse.SelectedItem.Text;
            int courseid =Convert.ToInt32( ddlcourse.SelectedValue);
            string name = txt_studentname.Text.Trim();
            string dob = txt_login_expiry_Date.Text.Trim();
            string gender = ddlgender.SelectedItem.Text;
            string fathername = txt_FatherName.Text.Trim();
            string occupation = txt_occupation.Text.Trim();
            string PresentAdd = txt_Presentadd.Text.Trim();
            string Email = txt_email.Text.Trim();
            Int64 emContact = Convert.ToInt64(txt_Emergency.Text.Trim());
            Int64 Phone = Convert.ToInt64(txt_Phone.Text.Trim());
            DateTime DateReg = DateTime.Today;
            string dateregistration = DateReg.ToShortDateString();
            if (Student.savedata(enrollment, Password, course, courseid,name, dob, gender, fathername, occupation, PresentAdd, Email, emContact, Phone) == true)
            {
                Session["EnrollmentNo"] = txtenrollment.Text;
                lbl_submit.ForeColor = System.Drawing.Color.Green;
                lbl_submit.Text = "Data Saved Successfully";
                ClearTextBox();
            }
            else
            {
                lbl_submit.ForeColor = System.Drawing.Color.Red;
                lbl_submit.Text = "Data Not Save TRY AGAIN !!!";
              
            }


        }
        catch (Exception ex)
        {
            lbl_submit.ForeColor = System.Drawing.Color.Red;
            lbl_submit.Text = ex.Message;
        }
        finally
        {
            if (ConnectionManager.con.State == ConnectionState.Open)
            {
                ConnectionManager.con.Close();
            }
        }
        #endregion

    }
    protected void txt_email_TextChanged(object sender, EventArgs e)
    {

    }
    

 
    protected void GridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
    {

    }
   
    protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e)
    {

    }
    protected void GridView1_SelectedIndexChanging(object sender, GridViewSelectEventArgs e)
    {

    }
    #region(Function For Fetching Course Name From Database)
    public void fillcourse()
    {

        try
        {
            ddlcourse.DataSource = Module.Bindcourse();
            ddlcourse.DataTextField = "CourseName";
            ddlcourse.DataValueField = "Id";
            ddlcourse.DataBind();
            ddlcourse.Items.Insert(0, new ListItem("----Select----", "0"));

        }
        catch (Exception ex)
        {

        }
        finally
        {
            ConnectionManager.con.Close();
        }
    }
    #endregion

    protected void ddlgender_SelectedIndexChanged(object sender, EventArgs e)
    {
        lbl_submit.Text = "";
    }
    protected void ddlcourse_SelectedIndexChanged(object sender, EventArgs e)
    {
        regno();
    }
    #region(Function For AutoGenerated EnrollmentNo)
    public void regno()
    {
       string course=ddlcourse.SelectedItem.Text;
       txtenrollment.Text = Student.autogenEnrollmentno("SMS", course);
       // txtenrollment.Text = txtenrollment.Text.Remove(1,1);
    }
    #endregion
}
